package de.hahn.blog.adfrestmethod.RESTmodel.views.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Jan 30 16:18:08 CET 2020
// ---------------------------------------------------------------------
public interface EmployeesView extends ViewObject {
    String getVersionInfo();

    String sayHello(String name);
}

